[package]
name = "gitday"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
structopt = "0.3.26"
chrono = "0.4"
